### ISSUE TITLE
running 

### ISSUE THREAD

**Issue by xinzheng798** [tudelft3d/City3D#20]
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: dexp != 2047
File: /usr/local/include/CGAL/Mpzf.h
Line: 445
Explanation: Creating an Mpzf from infinity or NaN.

**Comment by xinzheng798** [comment]
CLI_EXAMPLE2

**Comment by LiangliangNan** [comment]
Hi @xinzheng798, thanks for reporting this issue. 
But without useful information, we will not be able to investigate it. Can you provide the following informaiton?

**Describe the bug**
A clear and concise description of what the bug is.
If applicable, add screenshots (of the results or error messages) to help explain your problem.

**Tell us how to reproduce the bug**
Steps to reproduce the behavior:
1. Load the data file `xxx.bvg`. If applicable, post here a copy of the data for reproducing the issue.
2. Click on '....'
3. See error. A clear and concise description of what you expected to happen.

**Development/Running environment:**
 - OS: [e.g. Windows 10, macOS 11.6]
 - Compiler [e.g. MSVC 2019, Clang 11, GCC 10]
 - Debug or release?

**Additional context**
Add any other context about the problem here.

**Comment by xinzheng798** [comment]
Describe the bug
![eeeor](https://user-images.githubusercontent.com/125725219/233997206-515757af-9864-4aea-b512-8f359a46f878.png)
individual building dataset:file:
[building_instances1.zip](https://github.com/tudelft3d/City3D/files/11310478/building_instances1.zip)

Tell us how to reproduce the bug
1.build CLI_EXAMPLE_2(Debug),use CLion
2.modify the data path 
3.running 

Development/Running environment:
Ubuntu 20.04
CLion
Compiler :ninja

**Comment by xinzheng798** [comment]
@yidahuang Thank you most sincerely.I know the problem
