### ISSUE TITLE
[BUG] - How to get the bottom profile data

### ISSUE THREAD

**Issue by WS517** [tudelft3d/City3D#43]
Dear Professor, I want to input the large-scale scene point cloud for modeling, but I only have point cloud data, no bottom contour data, I tried to utilize [CLI_Example_1](https://github.com/tudelft3d/City3D/tree/main/code/CLI_Example_1), but failed, how should I get the bottom contour data?

**Comment by LiangliangNan** [comment]
Please read the ReadMe file carefully because it tells when to use what.
Again:
 - [CLI_Example_1](https://github.com/tudelft3d/City3D/tree/main/code/CLI_Example_1) is suitable for data with footprint. You can use whatever method or data sources to obtain the footprint.
 - [CLI_Example_2](https://github.com/tudelft3d/City3D/tree/main/code/CLI_Example_2) is suitable for data without footprint. Besides, the input must be point clouds of individual buildings. You can use whatever method accessible to you to segment the point cloud into individual buildings.

**Comment by WS517** [comment]
Thanks for your answer, but I was wondering if it is possible to use [CLI_Example_1](https://github.com/tudelft3d/City3D/tree/main/code/CLI_Example_1) or [CLI_Example_2](https://github.com/tudelft3d/City3D/tree/main/code/CLI_Example_2) or [City3D-GUI](https://github.com/tudelft3d/City3D/tree/main/code/City3D) to get the footprint data of the input large field attraction cloud? Looking forward to your reply, thank you very much!

**Comment by LiangliangNan** [comment]
City3D focuses on the reconstruction (i.e., converting 3D points to mesh models), rather than the segmentation.
However, it does provide functionalities that could extract footprint for individual buildings (but not for entire scenes).

**Comment by WS517** [comment]
Thanks for your answer,but I would like to know how did you get the footprint data of your large-scale raw input point clouds.Looking forward to your reply, thank you very much!

**Comment by LiangliangNan** [comment]
What I know that might have footprint data:
 - The cadaster of city/country. Many countries have the footprint data, most of which are managed by the cadaster. The cadaster may have already made such data public, or you can contact them for more details.
 - Some open data platforms, e.g., OpenStreetMap, offer footprint data. What I know is https://tudelft3d.github.io/3dfier/building_footprints_from_openstreetmap.html
 - Many published papers address instance segmentation of urban buildings from point clouds. You can try any of these methods and see if it meets the requirement.
