### ISSUE TITLE
Point cloud data testing

### ISSUE THREAD

**Issue by najsdh** [tudelft3d/City3D#44]
![图片1](https://github.com/tudelft3d/City3D/assets/135418424/67e0112c-f883-4263-9f76-1c9d87a1bc80)
I would like to ask why such a point cloud input into the program crashed. I thought it was because the amount of data was too large, so I diluted the point cloud, but the program still crashed after entering the point cloud

**Comment by LiangliangNan** [comment]
By "entering the point cloud", did you mean the program crashes when loading the data?
If so, can you post your point cloud here so we can debug it?

**Comment by najsdh** [comment]
[plydata.zip](https://github.com/tudelft3d/City3D/files/15244827/plydata.zip)
Hello, this is the code I input for the test, please help me to see if there is any problem. If there is a problem, how can I adjust it so that it can reconstruct the model. These point cloud data are a building that I intercepted from a whole block of point cloud data, maybe the roof is noisy and irregular.

**Comment by LiangliangNan** [comment]
Your ZIP file contains multiple PLY fiels, which one should be used?
Beside, you mentioned "this is the code", did you mean you make changes to the City3D code? If so, what changes did you make?
Anyway, to understand what your issue is, please precisely describe how others can reproduce your issue.

**Comment by najsdh** [comment]
I'm sorry, I may have misstated that. What I want to say is that this is the point cloud data that I used for testing, and I seem to have failed to reconstruct every single one of them. I would also like to know how the height of the reconstructed building is obtained if only the point cloud data of the roof is tested.

**Comment by LiangliangNan** [comment]
I still don't understand what your issue was. You mentioned the program crashed and failed for all the test examples. 
Anyway, I quickly tested with your data and found the it worked well. Below are the snapshots for building 1 and building 2.

Building 1:
![build1](https://github.com/tudelft3d/City3D/assets/15526536/b1276d08-1295-41ac-9c82-852a89e31967)

Building 2:
![build2](https://github.com/tudelft3d/City3D/assets/15526536/d3a27fee-d7d0-47dc-81d4-251bf4cace45)

The results seem quite good give the very low quality of the input point clouds.
Besides, the method also assumes the ground plane is at Z=0, but it seems your point clouds may have some aribitrary translations.

**Comment by najsdh** [comment]
Thank you. Maybe there's something wrong with the way I handled it. Let me check it again. Thank you very much for your help
