### ISSUE TITLE
Validation: Calculation RMSE between point clouds and reconstructed model.

### ISSUE THREAD

**Issue by QiaosiLi** [tudelft3d/City3D#45]
We used LiDAR point clouds and city3d to construct building models. As we don't have ground truth data, we would like to calculate the RMSE between point clouds and constructed models to evaluate the reconstruction results as you mentioned in your paper. We only found some libraries that can calculate the distance between two point clouds instead of the point cloud to mesh. As we lack experience in this field, could you share how you calculate the RMSE in your work? If you know any open-source codes about this, it would be great if you could share them with us. Thanks a lot.

**Comment by LiangliangNan** [comment]
This question seems not relevant to the core methodology of City3D. 

RMSE is a measure of the overall difference between the point cloud and the reconstructed mesh.
When calculating RMSE between a reconstructed mesh and the input point cloud, we might need to look into two directional RMSE: from the mesh to the point cloud and from the point cloud to the mesh. 
- Mesh to Point Cloud RMSE: Calculate the RMSE from each vertex in the mesh to its nearest neighbor in the point cloud.
- Point Cloud to Mesh RMSE: Calculate the RMSE from each point in the point cloud to its nearest face in the mesh.

Since our primary goal is to evaluate the accuracy of the reconstructed mesh, it should be sufficient to use the Mesh to Point Cloud RMSE. We also see in some other papers researchers used Point Cloud to Mesh RMSE. Of course, you may also combine them by calculating their average.
