### ISSUE TITLE
[BUG] - put here a short description of the issue

### ISSUE THREAD

**Issue by najsdh** [tudelft3d/City3D#47]
Hello Teacher Nan, I've encountered a new issue. It seems like the footprint I generated for this building matches correctly with the building's point cloud data when viewed in other software. However, when I input it into City3D software, it seems like both the point cloud and the footprint data disappear. I'm wondering if this is a projection issue. Below are my building point cloud and footprint data.
[data.zip](https://github.com/tudelft3d/City3D/files/15263920/data.zip)

**Comment by yidahuang** [comment]
![CleanShot 2024-05-15 at 11 19 09@2x](https://github.com/tudelft3d/City3D/assets/18398235/d3f79b0f-a26a-4134-960e-3568aebca054)
I quickly checked your data. The raw data in .las format usually represents a very large area of urban scenes, and some coordinates may have very large values. To render it in OpenGL, we translate it using the coordinates of the first point in the point cloud when loading the data.

The current implementation doesn't translate the .obj footprint data with the first point, which is why they look disappear. A quick way to solve this is to export your .las point cloud into .ply format; this way, the data will not be translated.

![CleanShot 2024-05-15 at 12 35 39@2x](https://github.com/tudelft3d/City3D/assets/18398235/4822144a-40da-4e88-8fa9-b2d8e9fd1a14)

**Comment by najsdh** [comment]
Thank you, Teacher Huang. I'm very grateful for your response. I've tried to reconstruct the data, but I've found that due to the poor quality of the point cloud, reconstruction takes a long time, especially when dealing with complex buildings, and sometimes the program gets stuck. After reviewing some previous questions, I suspect that there may be too many initially detected roof planes. So, I wanted to ask if it's possible to modify certain parameters in the code to reduce the number of fitted planes, thus facilitating the model's reconstruction. Additionally, I've noticed that adjusting these parameters also affects the reconstruction speed. I'd like to know the specific roles of these parameters and how to modify them to better suit my data. I'm looking forward to your response. Wishing you a pleasant life and smooth work.

**Comment by najsdh** [comment]
![image](https://github.com/tudelft3d/City3D/assets/135418424/ff64d67b-d594-451f-ac75-24c3d95a3f65)

**Comment by yidahuang** [comment]
If you want a detailed description of parameters, please directly read our paper.
For parameters tunning, you can refer to issue #4 , #18 and #36, we have explained how to tune the parameters for their cases.
In your case, maybe you can increase the parameter "Number" for plane detection.
Honestly speaking, the quality of data you provided is very poor,  it is hard to recognize the roof planes even for human eyes.
