### ISSUE TITLE
Can the program handle footprint (.geojson) that contain ring holes ? 

### ISSUE THREAD

**Issue by wfq007** [tudelft3d/City3D#53]

**Comment by yidahuang** [comment]
Hi, sorry for the late response. Our program only supports simple polygon footprints, meaning they must be non-self-intersecting and without holes.

**Comment by LiangliangNan** [comment]
To be clear, our algorithm (described in the paper) is able to handle footprint polygons with holes. 
However, this implementation (in this repository) doesn't support such complex footprints due to the limitation of the used data structure (i.e., a footprint polygon is stored as a polygonal face of a mesh, easier for visualization). 
To allow handling footprints with holes, you can modify the data structure of `Map` in our implementation. Alternatively (and also the easiest), you can introduce a per-face attribute to store the holes. Then, in the hypothesis generation step, the vertical planes derived from the holes should also be provided (together with other vertical planes derived from the outer polygon of the footprint).
